// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GradientExplorer
{
    internal sealed partial class Vsix
    {
        public const string Id = "GradientExplorer.51c22098-daf1-4f4a-b455-37ff8586533e";
        public const string Name = "GradientExplorer";
        public const string Description = @"Converts Forward functions into gradient functions.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "ameritusweb@gmail.com";
        public const string Tags = "";
    }
}
